### PR TITLE
Bug Fix/ refactoring/ feature enhancement

### PR DESCRIPTION
**Pull request by jBouyoud**
I know that this PR is a little bit huge, but you can review it commit by commit. Each commit comment aims to define as well as i can the purpose of it's content.

This PR contains 3 topics: 
* First a bug fix on send data.
* Secondly a refactoring which intent is to try separate core logic of features (attributes parsing, commands, ...) in order to improve maintenability.
* Add some new features (identification, zigate command, level controls, generic attribute parsing)

If this PR is too huge, I can separate it in a smaller ones.

I hope this helps
Regards

### CODE REVIEW

**Review by elric91 — APPROVED** [review]
Seems good to me
Will commit first the updates which do not impact core logic : would you mind doing a PR with features not needing refactoring first ? (I'd like to test non-regression on added feature before pushing the refactor)

Regarding refactoring, we need to have Vesa review it also to all agree on the way we want to move the refactor (i.e. the split you did with the classes is becoming necessary). What I already had in mind about refactoring : 
- use decorators & registers to make the declaration on new clusters or attributes more clear
- define default log generation (based on the OrderedDict), which can be overridden only when needed (in order to lighten the code from all these ZGT_LOG)
- use of struct() to ease decoding of messaging

If everyone is OK, I propose to : 
1. Add only features (no refactor) & test. If no major bug is found, I'll give you the right to commit to help directly with further merges
2. Add refactor (as you proposed)
3. Work then only on further refactoring
All keeping in mind that it must still work with the homeassistant plugin :sweat_smile:

**Review by ISO-B — APPROVED** [review]
Sorry took bit before I had time to see changes. Yes changes look good. I think it's actually good idea to split things to smaller files.

Maybe we should first make new branch and merge this PR to it. Then we could test and verify that everything is still working. After that just merge it to master.

**Comment by jBouyoud** [comment]
Good :)
If you are agree :
I can make another PR with only 4aed9ca and 5453863, 
I can integrates latest changes on horizontal movements on this PR
You can change the target branch of this PR.

**Comment by elric91** [comment]
don't work too much in advance ;)
I started an 'unstable branch' for refactoring as I was not 100% satisfied with the Mixin approach : 
- responses have already been restructured through dedicated classes (combined in a dictionary for ref). Still need to port the last responses in the proper format now that I have tested it
- I started the same with cluster but I wonder if managing it at attribute level would be better
- at the same time, I was reintegrating all your enhancements
--> the idea is to have a dict in which clusters / attributes can be registered (so no need to touch main code each time we implement a new device)

If you can have a look at how the responses have been restructured, feedback is welcome

**Comment by max5962** [comment]
news about that pull request ? :)

**Pull request closed without merging**
