### PR TITLE
Add Link Quality value on device attribute

### PR DESCRIPTION
**Pull request by max5962**
Hello,
My first pull request :)
Some code in order to add Link Quality on device attribute.

### CODE REVIEW

**Review by ISO-B — CHANGES_REQUESTED** [review]
- Fix formatting to PEP8.
- Set_device_property's third parameter property_id should not include space
- Maybe link quality could be set also when there is no link. Otherwise device info shows link quality even if link is dead.

**Comment by max5962** [comment]
Thanks for the review

- Never wrote python code, so i will lean about PEP8
- I will do that
- So if link quality = 255 set "0" ?

**Comment by lolorc** [comment]
what's the meaning of link_quality == 255 ?
does that really mean you won't find a corresponding endpoint ?

**Comment by max5962** [comment]
link_quality == 255
always (in my case)  mean that the zigate lose temporary the connection to the device.

**Comment by max5962** [comment]
if i do not have regressions, i will do a new pull request tomorrow

**Comment by max5962** [comment]
can be merged :)

**Comment by max5962** [comment]
@ISO-B 
I also update the "last seen" value when the RSSI is updated in order to push automatically the new value to grafana / influxdb ( instead of waiting the next status change ) .

**Comment by max5962** [comment]
@ISO-B @elric91 
Is it OK now ? 
if it's ok i'd like to implement battery % in hass.

**Pull request merged**
